---
- name: Reset worker server
  hosts: workers
  become: true
  tasks:
    - include: task/uninstall-kubeadm.yml
    - include: task/uninstall-docker.yml
    - include: task/uninstall-nfs-client.yml

- name: Reset master server
  hosts: masters
  become: true
  tasks:
    - include: task/uninstall-kubeadm.yml
    - include: task/uninstall-docker.yml
    - include: task/uninstall-nfs-server.yml

- name: Reset gitlab server
  hosts: gitlab
  become: true
  tasks:
    - include: task/uninstall-gitlab.yml

- name: Reset jenkins server
  hosts: jenkins
  become: true
  tasks:
    - include: task/uninstall-jenkins.yml
    - include: task/uninstall-docker.yml

- name: Reset harbor server
  hosts: harbor
  become: true
  tasks:
    - include: task/uninstall-harbor.yml
    - include: task/uninstall-docker.yml