---
- name: Reset harbor server
  hosts: harbor
  become: true
  tasks:
    - include_tasks: task/uninstall-harbor.yml
    - include_tasks: task/uninstall-docker.yml

- name: Reset jenkins server
  hosts: jenkins
  become: true
  tasks:
    - include_tasks: task/uninstall-jenkins.yml
    - include_tasks: task/uninstall-docker.yml
    - include_tasks: task/uninstall-jdk.yml

- name: Reset gitlab server
  hosts: gitlab
  become: true
  tasks:
    - include_tasks: task/uninstall-gitlab.yml

