---
- name: Reset worker server
  hosts: workers
  become: true
  tasks:
    - include_tasks: task/uninstall-kubeadm.yml
    - include_tasks: task/uninstall-docker.yml
    - include_tasks: task/uninstall-nfs-client.yml

- name: Reset master server
  hosts: masters
  become: true
  tasks:
    - include_tasks: task/uninstall-kubeadm.yml
    - include_tasks: task/uninstall-docker.yml
    - include_tasks: task/uninstall-nfs-server.yml