---
- name: Install gitlab server
  hosts: gitlab
  become: true
  tasks:
    - include: task/install-gitlab.yml
    # ---------------------------------------------------------------------------

- name: Install jenkins server
  hosts: jenkins
  become: true
  tasks:
    - include: task/install-docker.yml
    - include: task/install-jdk.yml
    - include: task/install-jenkins.yml
    # ---------------------------------------------------------------------------

- name: Install harbor server
  hosts: harbor
  become: true
  tasks:
    - include: task/install-docker.yml
    - include: task/install-harbor.yml
    # ---------------------------------------------------------------------------
