---
- name: Install master servers
  hosts: masters
  become: true
  tasks:
    - include_tasks: task/install-os-patches.yml
    - include_tasks: task/install-docker.yml
    - include_tasks: task/install-kubeadm.yml
    # ---------------------------------------------------------------------------
    - include_tasks: task/install-nfs-server.yml
    - include_tasks: task/install-kubernetes-cluster.yml
    - include_tasks: task/install-kubernetes-cni.yml
    - include_tasks: task/generate-join-command.yml

- name: Install worker servers
  hosts: workers
  become: true
  tasks:
    - include_tasks: task/install-os-patches.yml
    - include_tasks: task/install-docker.yml
    - include_tasks: task/install-kubeadm.yml
    # ---------------------------------------------------------------------------
    - include_tasks: task/install-nfs-client.yml
    - include_tasks: task/join-kubernetes-cluster.yml

- name: Install kubernetes addons
  hosts: masters
  become: true
  tasks:
    - include_tasks: task/install-helm.yml
    - include_tasks: task/install-nfs-subdir-external-provisioner.yml
    - include_tasks: task/install-metrics-server.yml
    - include_tasks: tash/install-ingress-nginx.yml
    - include_tasks: tash/install-cert-manager.yml
    - include_tasks: tash/install-dashboard.yml

- name: Install data center
  hosts: masters
  become: true
  tasks:
    - include_tasks: tash/install-data-center.yml

