# Install Istio
- name: Install Istio
  shell: |
    helm repo add istio https://istio-release.storage.googleapis.com/charts
    helm repo update
    kubectl create namespace istio-system
    helm upgrade --install istio-base istio/base -n istio-system
    helm upgrade --install istiod istio/istiod -n istio-system
    kubectl create namespace istio-ingress
    kubectl label namespace istio-ingress istio-injection=enabled
    helm upgrade --install istio-ingress istio/gateway -n istio-ingress

# Install Kiali, Prometheus, Grafana, Jaeger.