# Install ingress nginx
- name: Install ingress nginx
  shell: |
    kubectl create ns ingress-nginx
    helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
    helm upgrade ingress-nginx ingress-nginx/ingress-nginx --install \
      --namespace ingress-nginx \
      --set controller.hostNetwork=true \
      --set controller.dnsPolicy=ClusterFirstWithHostNet \
      --set controller.kind=DaemonSet \
      --set controller.reportNodeInternalIp=true \
      --set controller.image.registry=registry.aliyuncs.com \
      --set controller.image.image=google_containers/nginx-ingress-controller \
      --set controller.image.tag=v1.8.1 \
      --set controller.image.digest=null \
      --set controller.admissionWebhooks.patch.image.registry=registry.aliyuncs.com \
      --set controller.admissionWebhooks.patch.image.image=google_containers/kube-webhook-certgen \
      --set controller.admissionWebhooks.patch.image.tag=v20230407 \
      --set controller.admissionWebhooks.patch.image.digest=null

