# Install Docker and its dependent components
- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - gnupg-agent
      - lsb-release
      - software-properties-common

- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Get linux distribution
  shell: |
    . /etc/os-release
    echo $VERSION_CODENAME
  register: linux_codename

- name: Add apt repository for Docker
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu "{{ linux_codename.stdout }}" stable
    state: present
    filename: docker

- name: Install docker and its dependecies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - docker-ce=5:{{ docker_version }}~3-0~ubuntu-{{ linux_codename.stdout }}
      - docker-ce-cli=5:{{ docker_version }}~3-0~ubuntu-{{ linux_codename.stdout }}
      - containerd.io
      - docker-buildx-plugin
      - docker-compose
      - docker-compose-plugin

- name: Docker daemon.json
  vars:
    docker_daemon: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2",
        "insecure-registries": ["{{ hostvars['harbor'].ansible_host }}:{{ harbor_port }}", "0.0.0.0"],
        "registry-mirrors": [
          "https://registry.docker-cn.com",
          "https://hub-mirror.c.163.com"
        ],
        "hosts": ["tcp://0.0.0.0:2375", "unix:///var/run/docker.sock"]
      }
  copy:
    dest: /etc/docker/daemon.json
    content: "{{ docker_daemon | to_nice_json }}"

- name: Ceeate docker service systemd directory
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory
    mode: '0755'

- name: Config docker service systemd
  copy:
    dest: /etc/systemd/system/docker.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd

- name: Restart docker
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
