# Install NFS Subdirectory External Provisioner
- name: Install NFS Subdirectory External Provisioner
  shell: |
    helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    helm upgrade --install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
      --version {{ nfs_subdir_external_provisioner_chart_version }} \
      --namespace kube-system \
      --set image.repository=eipwork/nfs-subdir-external-provisioner \
      --set image.tag={{ nfs_subdir_external_provisioner_version }} \
      --set storageClass.defaultClass=true
      --set nfs.server={{ hostvars['master'].ansible_host }} \
      --set nfs.path=/home/nfs