# Wait kubernetes control plane startup
- name: Wait kubernetes control plane startup
  wait_for:
    port: 6443
    delay: 5

# Setup the container networking provider and the network policy engine
- name: Install calico pod network
  shell: kubectl apply -f https://docs.projectcalico.org/archive/{{ calico_version }}/manifests/calico.yaml >> /tmp/pod_network_setup.log

# Names incorporating Firmware/BIOS provided index numbers for on-board devices (eno1)
# Names incorporating Firmware/BIOS provided PCI Express hotplug slot index numbers (ens1)
# Names incorporating physical/geographical location of the connector of the hardware (enp2s0)
# Names incorporating the interfaces's MAC address (enx78e7d1ea46da)
# Classic, unpredictable kernel-native ethX naming (eth0)
- name: Config calico IP_AUTODETECTION_METHOD
  shell: kubectl set env daemonset/calico-node -n kube-system IP_AUTODETECTION_METHOD=interface=en.*,eth.*
