# Install Docker and its dependent components
- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - gnupg-agent
      - lsb-release
      - software-properties-common

- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add apt repository for Docker
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    filename: docker

- name: Install docker and its dependecies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - docker-ce={{ docker_version }}
      - docker-ce-cli={{ docker_version }}
      - containerd.io

- name: Docker daemon.json
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2",
        "insecure-registries": ["{{ harbor_ip }}:{{ harbor_port }}", "0.0.0.0"],
        "registry-mirrors": [
          "https://registry.docker-cn.co",
          "https://hub-mirror.c.163.com"
        ],
        "hosts": ["tcp://0.0.0.0:2375", "unix:///var/run/docker.sock"]
      }

- name: Ceeate docker service systemd directory
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory
    mode: '0755'

- name: Config docker service systemd
  copy:
    dest: /etc/systemd/system/docker.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd

- name: Restart docker
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker

- name: Install docker compose
  shell: wget -nc https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64 -O /usr/local/bin/docker-compose
  register: wget_ret
  failed_when:
    - wget_ret.rc != 0
    - "'not retrieving' not in wget_ret.stderr"

- name: Apply docker compose executable permissions
  file:
    path: /usr/local/bin/docker-compose
    state: touch
    mode: u+x,g+x,o+x

- name: Symbolic link docker compose
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link