# Install Jenkins
- name: Add an apt signing key for Jenkins
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present
    keyring: /usr/share/keyrings/jenkins-keyring.asc

- name: Add apt repository for Jenkins
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
    state: present
    filename: jenkins

- name: Install docker and its dependecies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - jenkins