# Initialize the Kubernetes cluster with kubeadm
- name: Pull kubernetes image ahead (need few minutes)
  shell: kubeadm config images pull --image-repository registry.aliyuncs.com/google_containers >> /tmp/kubeadm-init.log

- name: Initialize the Kubernetes cluster using kubeadm
  shell: kubeadm init --kubernetes-version $(kubeadm version -o short) --control-plane-endpoint {{ hostvars['master'].ansible_host }} --pod-network-cidr=192.168.0.0/16 --image-repository registry.aliyuncs.com/google_containers >> /tmp/kubeadm-init.log

# Kubernetes cluster admin config
- name: Create .kube directory
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: Copies admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes
    mode: 0700