# Install Jenkins offline
- name: Download jenkins debian package
  shell: wget -nc https://mirrors.tuna.tsinghua.edu.cn/jenkins/debian-stable/jenkins_{{ jenkins_version }}_all.deb -O /opt/jenkins_{{ jenkins_version }}_all.deb
  register: wget_ret
  failed_when:
    - wget_ret.rc != 0
    - "'not retrieving' not in wget_ret.stderr"

- name: Ceeate jenkins service systemd directory
  file:
    path: /etc/systemd/system/jenkins.service.d/
    state: directory
    mode: '0755'

- name: Config jenkins service systemd
  copy:
    dest: /etc/systemd/system/jenkins.service.d/override.conf
    content: |
      [Service]
      Environment="JENKINS_PORT={{ jenkins_port }}"

- name: Install jenkins debian package
  shell: dpkg -i /opt/jenkins_{{ jenkins_version }}_all.deb

- name: Install jenkins
  shell: apt-get install -f

- name: Restart jenkins
  systemd:
    state: restarted
    daemon_reload: yes
    name: jenkins