# Fix bug for https://github.com/containerd/containerd/issues/4581
- name: Remove file /etc/containerd/config.toml
  file:
    path: /etc/containerd/config.toml
    state: absent

- name: Restart containerd
  systemd:
    state: restarted
    daemon_reload: yes
    name: containerd

# Initialize the Kubernetes cluster with kubeadm
- name: Initialize the Kubernetes cluster using kubeadm (need few minutes)
  shell: kubeadm init --kubernetes-version $(kubeadm version -o short) --control-plane-endpoint {{ kubernetes_master_ip }} --pod-network-cidr=192.168.0.0/16 --image-repository registry.aliyuncs.com/google_containers >> kubeadm-init.log

# Kubernetes cluster admin config
- name: Create .kube directory
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: Copies admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes
    mode: 0700