# Reset kubernetes
- name: Reset kubernetes
  shell: kubeadm reset --force
  register: reset_ret
  failed_when:
    - reset_ret.rc != 0
    - "'kubeadm: not found' not in reset_ret.stderr"

- name: Uninstall Kubernetes binaries
  apt:
    name: "{{ packages }}"
    state: absent
    update_cache: yes
  vars:
    packages:
      - kubelet
      - kubeadm
      - kubectl