- name: Uninstall docker and its dependecies
  apt:
    name: "{{ packages }}"
    state: absent
    update_cache: yes
  vars:
    packages:
      - docker-ce={{ docker_version }}
      - docker-ce-cli={{ docker_version }}
      - containerd.io

- name: Clean docker data
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/docker
    - /var/lib/containerd

- name: Uninstall docker compose
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/local/bin/docker-compose
    - /usr/bin/docker-compose