- name: Uninstall jenkins
  apt:
    name: "{{ packages }}"
    state: absent
    update_cache: yes
  vars:
    packages:
      - jenkins

- name: Clean jenkins data
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/jenkins
